{% set name = "kliff" %}
{% set version = "0.1.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ed03c33203be97695e8ac80051b300476c0ed8f0774770570901bde82462072a

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  skip: true  # [win or py<35]

requirements:
  build:
    - {{ compiler('cxx') }} 
  host:
    - python
    - pip
    - pybind11
  run:
    - python
    - scipy
    - pybind11
    - pytest
    - kimpy

test:
  imports:
    - kliff

about:
  home: https://github.com/mjwen/kliff
  license: CDDL-1.0
  license_family: OTHER
  license_file: LICENSE
  summary: 'KIM-based Learning-Integrated Fitting Framework (KLIFF).'

  description: |
    KLIFF is an interatomic potential fitting package that can be used to 
    fit physics-motivated (PM) potentials, as well as machine learning 
    potentials such as the neural network (NN) models.
  doc_url: https://kliff.readthedocs.io
  dev_url: https://github.com/mjwen/kliff

extra:
  recipe-maintainers:
    - jan-janssen
