{% set name = "kliff" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a69be927aa3c22b166e530fcbdfd74b192229d04efc14823deadf3b509d2d560

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [win or py<35]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - setuptools
    - pybind11
  run:
    - python
    - pip
    - scipy
    - pybind11
    - pytest
    - kimpy
    - requests
    - pyyaml
    - monty
    - loguru
    - numpy <2.0

test:
  imports:
    - kliff
  commands:
    - pip check

about:
  home: https://github.com/mjwen/kliff
  license: CDDL-1.0
  license_family: OTHER
  license_file: LICENSE
  summary: KIM-based Learning-Integrated Fitting Framework (KLIFF).

  description: |
    KLIFF is an interatomic potential fitting package that can be used to 
    fit physics-motivated (PM) potentials, as well as machine learning 
    potentials such as the neural network (NN) models.
  doc_url: https://kliff.readthedocs.io
  dev_url: https://github.com/mjwen/kliff

extra:
  recipe-maintainers:
    - jan-janssen
    - mjwen
